# Generated by Django 4.1.7 on 2023-06-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product_colors_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prodigi_order_id',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
