# Generated by Django 4.1.7 on 2023-06-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
