# Generated by Django 4.1.7 on 2023-06-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, default='images/noimage.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='images/noimage.jpg', null=True, upload_to='images/'),
        ),
    ]
