# Generated by Django 4.2.2 on 2023-06-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_article_main_image_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='general_location',
            field=models.CharField(default='City,Country', max_length=100),
        ),
    ]
